<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('permissions', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->string('role')->nullable();
            $table->boolean('view_dashboard')->default(false);
            $table->boolean('stock_tab')->default(false);
            $table->boolean('store_tab')->default(false);
            $table->boolean('reports_tab')->default(false);
            $table->boolean('products_tab')->default(false);
            $table->boolean('expenses_tab')->default(false);
            $table->boolean('logout_tab')->default(true);
            $table->boolean('new_sale')->default(false);
            $table->boolean('view_shop_stock')->default(false);
            $table->boolean('add_shop_stock')->default(false);
            $table->boolean('edit_shop_stock')->default(false);
            $table->boolean('view_store_stock')->default(false);
            $table->boolean('add_store_stock')->default(false);
            $table->boolean('edit_store_stock')->default(false);
            $table->boolean('view_spoilt_stock')->default(false);
            $table->boolean('record_spoilt_stock')->default(false);
            $table->boolean('delete_spoilt_stock')->default(false);
            $table->boolean('view_short_expiries')->default(false);
            $table->boolean('view_expired_stock')->default(false);
            $table->boolean('record_expired_stock')->default(false);
            $table->boolean('reconcile_shop_stock')->default(false);
            $table->boolean('reconcile_store_stock')->default(false);
            $table->integer('savereconcile_shop_stock')->default(0);
            $table->integer('savereconcile_store_stock')->default(0);
            $table->boolean('view_reconciliation_report')->default(false);
            $table->boolean('transfer_stock')->default(false);
            $table->boolean('receive_transferred_stock')->default(false);
            $table->boolean('view_stock_transfers')->default(false);
            $table->boolean('view_payment_options')->default(false);
            $table->boolean('add_payment_options')->default(false);
            $table->boolean('edit_payment_options')->default(false);
            $table->boolean('delete_payment_options')->default(false);
            $table->boolean('view_option_statement')->default(false);
            $table->boolean('view_currencies')->default(false);
            $table->boolean('view_customers')->default(false);
            $table->boolean('add_customers')->default(false);
            $table->boolean('edit_customers')->default(false);
            $table->boolean('delete_customers')->default(false);
            $table->boolean('view_customer_deposits')->default(false);
            $table->boolean('add_customer_deposits')->default(false);
            $table->boolean('edit_customer_deposits')->default(false);
            $table->boolean('delete_customer_deposits')->default(false);
            $table->boolean('view_customer_balances')->default(false);
            $table->boolean('view_suppliers')->default(false);
            $table->boolean('add_suppliers')->default(false);
            $table->boolean('edit_suppliers')->default(false);
            $table->boolean('delete_suppliers')->default(false);
            $table->boolean('view_supplier_deposits')->default(false);
            $table->boolean('add_supplier_deposits')->default(false);
            $table->boolean('edit_supplier_deposits')->default(false);
            $table->boolean('delete_supplier_deposits')->default(false);
            $table->boolean('view_audits')->default(false);
            $table->boolean('view_cash_in')->default(false);
            $table->boolean('add_cash_in')->default(false);
            $table->boolean('edit_cash_in')->default(false);
            $table->boolean('delete_cash_in')->default(false);
            $table->boolean('view_cash_out')->default(false);
            $table->boolean('add_cash_out')->default(false);
            $table->boolean('edit_cash_out')->default(false);
            $table->boolean('delete_cash_out')->default(false);
            $table->boolean('view_money_transfers')->default(false);
            $table->boolean('add_money_transfers')->default(false);
            $table->boolean('edit_money_transfers')->default(false);
            $table->boolean('delete_money_transfers')->default(false);
            $table->boolean('view_expenses')->default(false);
            $table->boolean('add_expenses')->default(false);
            $table->boolean('edit_expenses')->default(false);
            $table->boolean('delete_expenses')->default(false);
            $table->boolean('view_expense_categories')->default(false);
            $table->boolean('add_expense_categories')->default(false);
            $table->boolean('edit_expense_categories')->default(false);
            $table->boolean('delete_expense_categories')->default(false);
            $table->boolean('view_expenses_report')->default(false);
            $table->boolean('view_products')->default(false);
            $table->boolean('add_products')->default(false);
            $table->boolean('edit_products')->default(false);
            $table->boolean('delete_products')->default(false);
            $table->boolean('view_business_products')->default(false);
            $table->boolean('add_business_products')->default(false);
            $table->boolean('edit_business_products')->default(false);
            $table->boolean('delete_business_products')->default(false);
            $table->boolean('view_product_categories')->default(false);
            $table->boolean('add_product_categories')->default(false);
            $table->boolean('edit_product_categories')->default(false);
            $table->boolean('delete_product_categories')->default(false);
            $table->boolean('view_product_units')->default(false);
            $table->boolean('add_product_units')->default(false);
            $table->boolean('edit_product_units')->default(false);
            $table->boolean('delete_product_units')->default(false);
            $table->boolean('view_units')->default(false);
            $table->boolean('add_units')->default(false);
            $table->boolean('edit_units')->default(false);
            $table->boolean('delete_units')->default(false);
            $table->boolean('view_services')->default(false);
            $table->boolean('view_sales_report')->default(false);
            $table->boolean('view_purchases_report')->default(false);
            $table->boolean('view_debtors_report')->default(false);
            $table->boolean('clear_debtors')->default(false);
            $table->boolean('clear_creditors')->default(false);
            $table->boolean('view_creditors_report')->default(false);
            $table->boolean('view_sales_analysis')->default(false);
            $table->boolean('edit_sales')->default(false);
            $table->boolean('delete_sales')->default(false);
            $table->boolean('edit_sales_amountpaid')->default(false);
            $table->integer('edit_selling_price')->default(0);
            $table->boolean('edit_purchase')->default(false);
            $table->boolean('delete_purchase')->default(false);
            $table->boolean('edit_purchase_amountpaid')->default(false);
            $table->boolean('manage_permissions')->default(false);
            $table->boolean('view_users')->default(false);
            $table->boolean('add_users')->default(false);
            $table->boolean('edit_users')->default(false);
            $table->boolean('delete_users')->default(false);
            $table->boolean('view_user_roles')->default(false);
            $table->boolean('add_user_roles')->default(false);
            $table->boolean('edit_user_roles')->default(false);
            $table->boolean('delete_user_roles')->default(false);
            $table->boolean('view_held_sales')->default(false);
            $table->boolean('view_messages')->default(false);
            $table->boolean('view_general_settings')->default(false);
            $table->boolean('view_receipt_settings')->default(false);
            $table->boolean('view_lpo')->default(false);
            $table->boolean('remove_expired_stock')->default(false);
            $table->boolean('advanced_features_tab')->default(false);
            $table->boolean('advanced_reports_tab')->default(false);
            $table->integer('consumables_tab')->default(0);
            $table->boolean('view_advanced_sales_report')->default(false);
            $table->boolean('view_advanced_purchases_report')->default(false);
            $table->boolean('view_advanced_debtors_report')->default(false);
            $table->boolean('view_advanced_creditors_report')->default(false);
            $table->boolean('view_advanced_stock_transfers')->default(false);
            $table->boolean('view_advanced_held_sales')->default(false);
            $table->boolean('view_advanced_expenses_report')->default(false);
            $table->integer('view_transactions_report')->default(0);
            $table->integer('view_income_statement')->default(0);
            $table->integer('view_product_demand_report')->default(0);
            $table->integer('view_purchase_payments_report')->default(0);
            $table->integer('view_profitanalysis_report')->default(0);
            $table->integer('add_consumable_items')->default(0);
            $table->integer('stocking_consumables')->default(0);
            $table->integer('using_consumables')->default(0);
            $table->integer('stocking_report')->default(0);
            $table->integer('usage_report')->default(0);
            $table->integer('edit_consumables')->default(0);
            $table->integer('delete_consumables')->default(0);
            $table->integer('view_purchasereturns_report')->default(0);
            $table->integer('view_salereturns_report')->default(0);
            $table->integer('confirm_spoilt_stock')->default(0);
            $table->integer('view_payments_report')->default(0);
            $table->integer('view_storeprice_changes')->default(0);
            $table->integer('view_shopprice_changes')->default(0);
            $table->integer('manage_accesstime')->default(0);
            $table->integer('edit_accesstime')->default(0);
            $table->integer('view_supplierbalances')->default(0);
            $table->integer('confirm_orders')->default(0);
            $table->integer('confirm_servedorders')->default(0);
            $table->integer('view_sellingprice_changes')->default(0);
            $table->integer('internaltransfer_stock')->default(0);
            $table->integer('directtransfer_stock')->default(0);
            $table->integer('view_advanced_shoppurchases_report')->default(0);
            $table->integer('view_advanced_storepurchases_report')->default(0);
            $table->integer('modify_sales')->default(0);
            $table->integer('modify_purchases')->default(0);
            $table->integer('view_user_summary')->default(0);
            $table->integer('view_general_summary')->nullable()->default(0);
            $table->integer('print_heldsales')->default(0);
            $table->integer('status')->default(1)->comment('0=inactive 1=active');
            $table->integer('user_id')->nullable();
            $table->integer('branch_id')->nullable();
            $table->integer('business_id')->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('permissions');
    }
};
